export const HTTP_MESSAGES = {
  EN: {

    AUTH_SUCCESS: "Authentication successful.",
    ALL_FEILEDS_REQUIRED:"All Feiled is Required",
    AUTH_ERROR: "Incorrect email or password.",
    USER_NOT_FOUND: "We're unable to find your account.",
    ROLE_NOT_FOUND: "We're unable to find your role.",
    SOMETHING_WENT_WRONG: "We encountered an error. Please try again later.",
    EMAIL_ALREADY_EXISTS:"Email Already Exists",
    LOGIN_SUCCESS : "User successfully logged in",
    TOKEN_INVALID: "Invalid token",
    TOKEN_EXPIRED : "Provided token has expired",
    ERROR : "ERROR",
    DATA_NOT_FOUND : "Data Not Found",
    DATA_ADDED_SUCCESS : "Data Added Successfully",
    DATA_FETCH_SUCCESS:"Data Fetch Successfully",
    DATA_ADDED_FAILED: "Data Added Failed",
    DATA_LIST_SUCCESS : "list fetch Successfully",
    DATA_GET_SUCCESS : "Data get Successfully",
    DATA_UPDATED_SUCCESS : "Data Updated Successfully",
    DATA_DELETED_SUCCESS : "Data Deleted Successfully",
    DATA_EXISTS_SUCCESS : "Data Already Exists",
    PROFILE_UPDATED_SUCCESS : "Profile updated successfully",
    NOT_AUTHORIZED : "You are not authorized to access this page",
    PROFILE_UPDATED_SUCCESSION : "Profile picture updated successfully",
    STATUS_SUCCESS_UPDATED : "Status updated Successfully",
    SERVER_ERROR:'Server Error',
    VEHICAL_DETAILS_SAVED : "Vehical details saved successfully",
    COMPANY_DETAILS_SAVED : "Company details saved successfully",
    GET_ALL_VEHICAL : "fetched all vehicals",
    VEHICAL_DELETED : "Vehical deleted successfully",
    VEHICAL_UPDATED : "Vehical updated successfully",
    VEHICAL_IMAGE_DELETED : "Vehical image deleted",
    OLD_PASSWORD_INC :"Old password is incorrect",
    PASSWORD_CHANGE_SUCCESSFUL: "Password changed successfully",
    INVALD_OTP: "Invalid OTP",
    EMAIL_IS_REQUIRED: "Email is required",
    OTP_SENTON_EMAIL: "OTP sent to your email (check console)" 
  }
};
